#!/usr/bin/env python3
"""
OOK.py 1.0

QuackSink Master Index Maker

Select a QuackSink archive root directory and collect each archive's .CARD
file into two master indexes:

    MASTER_INDEX.TXT
    MASTER_INDEX.JSON

Rules:
- A Windows folder-selection dialog chooses the archive root.
- Only direct child directories are treated as archives.
- Only the expected <archive-name>.CARD file in each direct child directory
  is collected.
- CARD contents are preserved verbatim in the TXT master index.
- The JSON master index stores each CARD as structured metadata plus its
  verbatim text.
- OOK does not read LOG.txt, .CONVO files, media, or any other archive file.
- OOK does not alter any CARD or archive contents.
- OOK rebuilds/overwrites the two master-index files in the selected root.
- Archives are ordered deterministically by archive directory name,
  case-insensitive.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
import tkinter as tk
from tkinter import filedialog, messagebox

PROGRAM_NAME = "OOK.py"
VERSION = "1.0"

MASTER_TXT = "MASTER_INDEX.TXT"
MASTER_JSON = "MASTER_INDEX.JSON"
CARD_SUFFIX = ".CARD"

CARD_HEADER_START = "<CARD HEADER START>"
CARD_HEADER_END = "<CARD HEADER END>"


def choose_root() -> Path | None:
    """Show a Windows folder picker and return the selected root directory."""
    root = tk.Tk()
    root.withdraw()
    root.attributes("-topmost", True)
    try:
        selected = filedialog.askdirectory(
            title=f"{PROGRAM_NAME} {VERSION} - Select QuackSink archive root"
        )
    finally:
        root.destroy()

    if not selected:
        return None

    return Path(selected)


def read_card(card_path: Path) -> str:
    """Read a CARD as text without altering its contents."""
    return card_path.read_text(encoding="utf-8", errors="replace")


def parse_card_metadata(card_text: str, archive_name: str) -> dict[str, str]:
    """Extract the small header metadata that OOK can reliably identify."""
    metadata: dict[str, str] = {
        "archive": archive_name,
        "format": "",
    }

    for raw_line in card_text.splitlines():
        line = raw_line.strip()
        if line.startswith("Archive:"):
            metadata["archive"] = line[len("Archive:") :].strip()
        elif line.startswith("Format:"):
            metadata["format"] = line[len("Format:") :].strip()

    return metadata


def collect_cards(root_dir: Path) -> tuple[list[dict], int]:
    """
    Collect cards from direct child archive directories.

    Returns:
        (entries, missing_card_count)
    """
    entries: list[dict] = []
    missing = 0

    children = sorted(
        (p for p in root_dir.iterdir() if p.is_dir()),
        key=lambda p: p.name.lower(),
    )

    print(f"{PROGRAM_NAME} {VERSION}")
    print(f"Root: {root_dir}")
    print(f"Direct child directories found: {len(children)}")
    print()

    for archive_dir in children:
        card_path = archive_dir / f"{archive_dir.name}{CARD_SUFFIX}"

        if not card_path.is_file():
            missing += 1
            print(f"[SKIP] {archive_dir.name} -> no expected .CARD")
            continue

        try:
            card_text = read_card(card_path)
        except OSError as exc:
            print(f"[ERROR] {archive_dir.name} -> could not read CARD: {exc}")
            continue

        metadata = parse_card_metadata(card_text, archive_dir.name)

        entries.append(
            {
                "archive": metadata["archive"],
                "format": metadata["format"],
                "card_file": card_path.name,
                "card_path": card_path.name,
                "card_text": card_text,
            }
        )

        print(f"[OK]   {archive_dir.name} -> {card_path.name}")

    return entries, missing


def write_master_txt(
    root_dir: Path,
    entries: list[dict],
) -> Path:
    """Write the human-readable master index."""
    output_path = root_dir / MASTER_TXT

    lines: list[str] = [
        "<MASTER INDEX HEADER START>\n",
        "QuackSink Master Archive Index\n",
        f"Generated by: {PROGRAM_NAME} {VERSION}\n",
        f"Generated: {datetime.now().astimezone().strftime('%Y-%m-%d %H:%M:%S %Z')}\n",
        f"Root: {root_dir}\n",
        f"Cards: {len(entries)}\n",
        "Format: 1\n",
        "<MASTER INDEX HEADER END>\n",
        "\n",
    ]

    for index, entry in enumerate(entries, start=1):
        lines.append(f"<CARD {index} START>\n")
        lines.append(f"Archive: {entry['archive']}\n")
        lines.append(f"Card: {entry['card_file']}\n")
        lines.append("\n")
        lines.append(entry["card_text"])
        if not entry["card_text"].endswith(("\n", "\r")):
            lines.append("\n")
        lines.append(f"<CARD {index} END>\n")
        lines.append("\n")

    output_path.write_text("".join(lines), encoding="utf-8", newline="\n")
    return output_path


def write_master_json(
    root_dir: Path,
    entries: list[dict],
) -> Path:
    """Write the machine-readable master index."""
    output_path = root_dir / MASTER_JSON

    generated_local = datetime.now().astimezone()

    payload = {
        "master_index": {
            "program": PROGRAM_NAME,
            "version": VERSION,
            "format": 1,
            "generated": generated_local.isoformat(),
            "root": str(root_dir),
            "card_count": len(entries),
        },
        "cards": entries,
    }

    output_path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    return output_path


def main() -> int:
    root_dir = choose_root()
    if root_dir is None:
        print("No archive root selected. Nothing done.")
        return 0

    if not root_dir.is_dir():
        messagebox.showerror(
            PROGRAM_NAME,
            f"Selected path is not a directory:\n\n{root_dir}",
        )
        return 1

    try:
        entries, missing = collect_cards(root_dir)
        txt_path = write_master_txt(root_dir, entries)
        json_path = write_master_json(root_dir, entries)
    except OSError as exc:
        print(f"\nFATAL: {exc}")
        try:
            messagebox.showerror(PROGRAM_NAME, str(exc))
        except tk.TclError:
            pass
        return 1
    except (TypeError, ValueError) as exc:
        print(f"\nFATAL: {exc}")
        try:
            messagebox.showerror(PROGRAM_NAME, str(exc))
        except tk.TclError:
            pass
        return 1

    print()
    print(f"Cards collected: {len(entries)}")
    print(f"Missing CARDs:    {missing}")
    print(f"TXT index:        {txt_path.name}")
    print(f"JSON index:       {json_path.name}")
    print("Done.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
